'''This module should be used to give you style feedback, and to test the 
parameter and return types of your functions. Before submitting your assignment, 
run this typechecker. This typechecker expects to find files flight_reader.py, 
flight_functions.py, and flight_types_constants_and_test_data.py in its folder.

Fixing all style errors and warnings generated by the "coding style" part of 
this checker will ensure you get most of your style marks. 

If errors occur when you run this typechecker, fix them before you submit
your assignment.

If no errors occur when you run this typechecker, then the type checks passed.
This means that the function parameters and return types match the assignment
specification, but it does not mean that your code works correctly in all
situations. Be sure to test your code thoroughly before submitting.
'''

import sys

sys.path.insert(0, './pyta')


print("================= Start: checking coding style =================")

import python_ta
python_ta.check_all('flight_reader.py', config='pyta/a3_pyta.txt')
python_ta.check_all('flight_functions.py', config='pyta/a3_pyta.txt')

print("================= End: checking coding style =================\n")


print("================= Start: checking parameter and return types =================")

import builtins
import copy
from io import StringIO

import flight_reader
import flight_functions
import flight_example_data as fdata

# Check for use of functions print and input.

our_print = print
our_input = input

def disable_print(*args):
    raise Exception("You must not call built-in function print!")

def disable_input(*args):
    raise Exception("You must not call built-in function input!")

builtins.print = disable_print
builtins.input = disable_input

# Type check the flight_reader.py functions

TYPECHECK_FEEBACK = 'The return type for {} should be {}, but your code returned {}'

# Type check flight_reader.read_airports
result = flight_reader.read_airports(fdata.create_airport_file())
assert isinstance(result, dict), \
    TYPECHECK_FEEBACK.format('read_airports', 'dict', type(result))
for key in result:
    assert isinstance(key, str), \
        TYPECHECK_FEEBACK.format('read_airports', 'dict with str keys', 'dict with ' + str(type(key)) + ' keys') 
    assert isinstance(result[key], dict), \
        TYPECHECK_FEEBACK.format('read_airports', 'dict with list values', 'dict with ' + str(type(result[key])) + ' values')  
    for inner_key in result[key]:
        assert isinstance(inner_key, str), \
            TYPECHECK_FEEBACK.format('read_airports', 'dict with inner dict that has str keys', 'dict with inner dict that has ' + str(type(key)) + ' keys') 
        assert isinstance(result[key][inner_key], str), \
            TYPECHECK_FEEBACK.format('read_airports', 'dict with inner dict that has list values', 'dict with inner dict that has ' + str(type(result[key])) + ' values')  
        

# Type check flight_reader.read_routes
result = flight_reader.read_routes(
    fdata.create_route_file(), fdata.create_example_airports())
assert isinstance(result, dict), \
    TYPECHECK_FEEBACK.format('read_routes', 'dict', type(result))
for key in result:
    assert isinstance(key, str), \
        TYPECHECK_FEEBACK.format('read_routes', 'dict with str keys', 'dict with ' + str(type(key)) + ' keys') 
    assert isinstance(result[key], list), \
        TYPECHECK_FEEBACK.format('read_routes', 'dict with list values', 'dict with ' + str(type(result[key])) + ' values') 


# Type check flight_reader.read_flights
result = flight_reader.read_flights(
    fdata.create_flight_file(), fdata.create_example_routes())
assert isinstance(result, list), \
    TYPECHECK_FEEBACK.format('read_flights', 'list', type(result))
for item in result:
    assert isinstance(item, dict), \
        TYPECHECK_FEEBACK.format('read_flights', 'list with dicts', 'list with ' + str(type(item)) + ' items')
    for key in item:
        assert isinstance(key, str), \
            TYPECHECK_FEEBACK.format('read_flights', 'dict with str keys', 'dict with ' + str(type(key)) + ' keys') 


# Type check the flight_functions.py functions

# Type check flight_functions.get_airport_info
airports = copy.deepcopy(fdata.create_example_airports())
result = flight_functions.get_airport_info(airports, 'AA1', 'Timezone')
assert isinstance(result, str), \
    TYPECHECK_FEEBACK.format('get_airport_info', 'str', type(result))
assert airports == fdata.create_example_airports(), \
       'get_airport_info should not mutate the parameter'

# Type check flight_functions.is_direct_flight
routes = copy.deepcopy(fdata.create_example_routes())
result = flight_functions.is_direct_flight('AA1', 'AA2', routes)
assert isinstance(result, bool), \
    TYPECHECK_FEEBACK.format('is_direct_flight', 'bool', type(result))
assert routes == fdata.create_example_routes(), \
       'is_direct_flight should not mutate the parameter'

# Type check flight_functions.is_valid_flight_sequence
routes = copy.deepcopy(fdata.create_example_routes())
result = flight_functions.is_valid_flight_sequence(['AA3', 'AA2', 'AA1'], routes)
assert isinstance(result, bool), \
    TYPECHECK_FEEBACK.format('is_valid_flight_sequence', 'bool', type(result))
assert routes == fdata.create_example_routes(), \
       'is_valid_flight_sequence should not mutate the parameter'

# Type check flight_functions.get_remaining_flights_today
flights = copy.deepcopy(fdata.create_example_flights())
result = flight_functions.get_remaining_flights_today(flights, 0.0)
assert isinstance(result, list), \
    TYPECHECK_FEEBACK.format('get_remaining_flights_today', 'list', type(result))
assert flights == fdata.create_example_flights(), \
       'get_remaining_flights_today should not mutate the parameter'

# Type check flight_functions.get_best_flight
flights = copy.deepcopy(fdata.create_example_flights())
result = flight_functions.get_best_flight('AA1', 'AA4', flights, 0.0)
assert isinstance(result, dict), \
    TYPECHECK_FEEBACK.format('get_best_flight', 'dict', type(result))
assert flights == fdata.create_example_flights(), \
       'get_best_flight should not mutate the parameter'

# Type check flight_functions.find_reachable_destinations
routes = copy.deepcopy(fdata.create_example_routes())
result = flight_functions.find_reachable_destinations('AA1', 0, routes)
assert isinstance(result, list), \
    TYPECHECK_FEEBACK.format('find_reachable_destinations', 'list', type(result))
assert isinstance(result[0], str), \
    TYPECHECK_FEEBACK.format('find_reachable_destinations', 'list of str', 'list of ' + str(type(result[0])))
assert routes == fdata.create_example_routes(), \
       'find_reachable_destinations should not mutate the parameter'

# Type check flight_functions.calculate_trip_time
flights = copy.deepcopy(fdata.create_example_flights())
result = flight_functions.calculate_trip_time(["AA1", "AA2"], flights)
assert isinstance(result, float), \
    TYPECHECK_FEEBACK.format('calculate_trip_time', 'float', type(result))
assert flights == copy.deepcopy(fdata.create_example_flights()), \
       'calculate_trip_time should not mutate the parameter'



builtins.print = our_print
builtins.input = our_input

print("================= End: checking parameter and return types =================\n")

print("The parameter and return type checker passed.")
print("This means we will be able to test your code.")
print("It does NOT mean your code is necessarily correct.")
print("You should run your own thorough tests to convince yourself your code is correct.")
print()
print("Scroll up to review the output of checking coding style.")
print("Make sure you scroll all the way to the top to see style checking for both files")
